version: "3.7"
services:
    tweet-producer:
        container_name: tweet-producer
        build:
            context: .
            dockerfile: ./docker/golang/Dockerfile
        image: producer:latest
        restart: always
        depends_on:
            - cassandra
        volumes:
            - "./producer/:/go/src/app"
        env_file: "./producer/configs/app.toml"
    cassandra:
        container_name: cassandra
        build:
            context: .
            dockerfile: ./docker/cassandra/Dockerfile
        image: cassandratweet:latest
        restart: always
        ports:
            - "9090:9090"
            - "7000:7000"
            - "7001:7001"
            - "7199:7199"
            - "9042:9042"
            - "9160:9160"
        # volumes:
