version: "3.7"
services:
    tweet-producer:
        container_name: tweet-producer
        build:
            context: .
            dockerfile: ./docker/golang/Dockerfile
        image: producer:latest
        restart: always
        depends_on:
            - cassandra
        volumes:
            - "./producer/:/go/src/app"
        env_file:
            - "./producer/configs/app.env"
            - "./docker/cassandra/cassandra.env"
    cassandra:
        container_name: cassandra
        build:
            context: .
            dockerfile: ./docker/cassandra/Dockerfile
        image: cassandratweet:latest
        restart: always
        env_file: "./docker/cassandra/cassandra.env"
        environment:
            - CASSANDRA_SEEDS=cassandra,cassandra2,cassandra3
    cassandra2:
        container_name: cassandra2
        build:
            context: .
            dockerfile: ./docker/cassandra/Dockerfile
        image: cassandratweet:latest
        restart: always
        env_file: "./docker/cassandra/cassandra.env"
        environment:
            - CASSANDRA_SEEDS=cassandra,cassandra2,cassandra3
    cassandra3:
        container_name: cassandra3
        build:
            context: .
            dockerfile: ./docker/cassandra/Dockerfile
        image: cassandratweet:latest
        restart: always
        env_file: "./docker/cassandra/cassandra.env"
        environment:
            - CASSANDRA_SEEDS=cassandra,cassandra2,cassandra3

