#!/bin/bash

# set default environment variables if not set
CASSANDRA_KEYSPACE=${CASSANDRA_KEYSPACE:=alpha}
CASSANDRA_TWEET_TABLE=${CASSANDRA_TWEET_TABLE:=tweet}
CASSANDRA_REPLICATION_STRATEGY=${CASSANDRA_REPLICATION_STRATEGY:='SimpleStrategy'}
CASSANDRA_REPLICATION_FACTOR=${CASSANDRA_REPLICATION_FACTOR:=1}

CQL=$(cat << cql
CREATE KEYSPACE $CASSANDRA_KEYSPACE WITH REPLICATION = {'class': '$CASSANDRA_REPLICATION_STRATEGY', 'replication_factor': $CASSANDRA_REPLICATION_FACTOR};
CREATE TABLE $CASSANDRA_KEYSPACE.$CASSANDRA_TWEET_TABLE(id UUID, created_at ascii, text text, PRIMARY KEY(id));
cql
)

echo -n "$CQL" > init.cql
